# Generated by Django 6.0.1 on 2026-02-16 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='billpayment',
            options={'ordering': ['-created_at'], 'verbose_name': 'Bill Payment', 'verbose_name_plural': 'Bill Payments'},
        ),
        migrations.AlterModelOptions(
            name='complaint',
            options={'ordering': ['-created_at'], 'verbose_name': 'Complaint', 'verbose_name_plural': 'Complaints'},
        ),
        migrations.AlterModelOptions(
            name='meterreading',
            options={'ordering': ['-created_at'], 'verbose_name': 'Meter Reading', 'verbose_name_plural': 'Meter Readings'},
        ),
        migrations.AlterModelOptions(
            name='poweroutage',
            options={'ordering': ['-created_at'], 'verbose_name': 'Power Outage Report', 'verbose_name_plural': 'Power Outage Reports'},
        ),
        migrations.AlterModelOptions(
            name='supportticket',
            options={'ordering': ['-created_at'], 'verbose_name': 'Support Ticket', 'verbose_name_plural': 'Support Tickets'},
        ),
        migrations.AddIndex(
            model_name='faq',
            index=models.Index(fields=['category'], name='myapp_faq_categor_46f03a_idx'),
        ),
        migrations.AddIndex(
            model_name='faq',
            index=models.Index(fields=['is_active'], name='myapp_faq_is_acti_fa7123_idx'),
        ),
    ]
